# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 128f766153cbee4fce46f13483975451692b829b8b8df89aba795e9d565999f5c93cec45e971b40298c61e4cf7572e6732ab8c83b8cc22bf56dfbc1fbc23ec3a

test:
  secret_key_base: 310d3cc0a680190fc03395f49f6dadcc62e7425c3108117a1441b4c9a52320a872586c494ea92858989643f48c8dc7673df3dcfaa18d48a95a582c75fe55dd79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
